### ISSUE TITLE
Error for running with TensorFlow: ValueError: Variable d_w1/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

### ISSUE THREAD

**Issue by heathervica** [jonbruner/generative-adversarial-networks#1]
Hello, please maybe could you help me? I had a running for running, I tried to figurate how to solve but I could not, I tried also with Python 2, 3.5, 3.6, And Tensorflow 1 and 1.1

The complete Error was:
heather@heather-ThinkPad-P50:~/Downloads/generative-adversarial-networks-master (2)$ python3 gan-script.py 
Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "gan-script.py", line 131, in <module>
    d_trainer_fake = tf.train.AdamOptimizer(0.0003).minimize(d_loss_fake, var_list=d_vars)
  File "/home/heather/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 325, in minimize
    name=name)
  File "/home/heather/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 446, in apply_gradients
    self._create_slots([_get_variable_for(v) for v in var_list])
  File "/home/heather/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/adam.py", line 122, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "/home/heather/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 766, in _zeros_slot
    named_slots[_var_key(var)] = slot_creator.create_zeros_slot(var, op_name)
  File "/home/heather/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py", line 174, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/home/heather/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py", line 146, in create_slot_with_initializer
    dtype)
  File "/home/heather/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py", line 66, in _create_slot_var
    validate_shape=validate_shape)
  File "/home/heather/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1049, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/heather/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 948, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/heather/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 356, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/heather/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 341, in _true_getter
    use_resource=use_resource)
  File "/home/heather/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 671, in _get_single_variable
    "VarScope?" % name)
ValueError: 
Variable d_w1/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by adeshpande3** [comment]
First, try restarting the kernel, and running the notebook again. A lot of times creating Tensorflow graphs in iPython notebooks can get a little messy.

If that doesn't fix it, this is most likely an issue with scope. I think that the new Tensorflow version deals with optimizers (other than GradientDescentOptimizer) a bit differently. I think adding this `with tf.variable_scope(tf.get_variable_scope(), reuse=False):` before the declaration of the Adam optimizer should fix the problem, but not completely sure if this is a long term solution. Have you come across this error @jonbruner

**Comment by jonbruner** [comment]
Adit is correct; this is usually a scope issue. When the Adam optimizer is instantiated, it creates a bunch of additional TensorFlow operations, and if TF thinks it can only reuse existing operations it throws an error.

I did come across this error and added the `with tf.variable_scope` line, which seemed to fix it. I'll try running again shortly to see if I can reproduce the error.

**Comment by jonbruner** [comment]
OK, I think I've fixed the problem in gan-script.py; TF v1.0 and v1.1 might handle variable scope in slightly different ways. The code previously worked in v1.0.1 but broke in v1.1.

In the revised script, variable scope is handled at a slightly higher level; `reuse_variables()` is false until after the optimizers are defined, at which point it's set to true for the rest of the script. The exception is the discriminator network, which is set up once with variable reuse off and a second time with variable reuse on.

@adeshpande3, would you mind running gan-script.py to make sure I didn't miss anything? I'll make the same changes to gan-script-fast.py now.

**Comment by jonbruner** [comment]
I've now updated [gan-script-fast.py](https://github.com/jonbruner/generative-adversarial-networks/blob/master/gan-script-fast.py) along the same lines, and I've tested it and [gan-script.py](https://github.com/jonbruner/generative-adversarial-networks/blob/master/gan-script.py) on both TF v1.0.1 and v1.1.0.

@heathervica, thanks for bringing this to our attention!

I'm going to go ahead and close this issue for now; @adeshpande3, let me know if you run into any problems when you run the files.

**Comment by heathervica** [comment]
Its running perfectly :), thank you so much
